### ISSUE TITLE
Contenido no migrado

### ISSUE THREAD

**Issue by cosmoscalibur** [fisicatyc/Seminario#1]
Esta pendiente la migración del [contenido existente en Google Sites/Drive](https://sites.google.com/site/fisicatyc/actividades-sftyc/seminario) al repositorio, en lo que respecta a las sesiones con código LaTeX existente o Notebooks.

**Comment by nicoguaro** [comment]
La idea es hacer un sitio web estático?

**Comment by cosmoscalibur** [comment]
No necesariamente, pero también podría ser bueno migrar el _site_. Cuando cree este repositorio era con el fin de pasar solo las notas de las sesiones cuyo fuente exista en el Drive del semillero.

**Comment by nicoguaro** [comment]
Ahhh, ok. Buena idea. A veces uno necesita las notas

**Comment by cosmoscalibur** [comment]
Como los usuarios activos en github no son integrantes activos del semillero, cierro el reporte.
